### ISSUE TITLE
Package requirements incompatible with existing conda environments

### ISSUE THREAD

**Issue by Lodewic** [EthanRosenthal/skits#14]
The requirements.txt file lists all required packages with specific required version numbers, `<pkgname>==<version>`. In some of my existing Conda environments this results in package version conflicts, where I don't think this package needs specific versions on all listed packages.

I think changing the requirements to use `>=` versions will make installing the package within existing environments more compatible. It also seems as if the only real requirements are numpy, scikit-learn and pytest, would reducing the requirements down to these 3 or so packages break the build?

I already have conda environments, most notable including `TSFRESH`.
In my Conda env, installing the package using `pip install -e .` as described in the README results in package version conflicts, and no installed `skits` package.

Minimal conda env I could recreate errors with:

From ./skits/ directory after cloning repo, on Windows 10

```
conda create -n skits-test python=3.7
conda activate skits-test
pip install tsfresh
pip install tensorflow
pip install -e .
``` 

Results in errors for me. My fastest workaround is to put your Python code in my project directory and using relative imports, but I would rather install the package properly.

**Comment by EthanRosenthal** [comment]
Yeah, I've been meaning to unpin the dependencies, split the requirements up into the regular requirements + development/testing requirements, and eventually package this repo up onto pypi. As a quick hack, you can modify the `requirements.txt` file and pip install the package locally. I'll try to unpin the dependencies soon.
